---
x-quorum-def:
  &quorum-def
  restart: "on-failure"
  build:
    context: config/goquorum
    args:
      QUORUM_VERSION: ${QUORUM_VERSION:-latest}
  expose:
    - 30303
    - 8545
  healthcheck:
    test: ["CMD", "wget", "--spider", "--proxy", "off", "http://localhost:8545"]
    interval: 3s
    timeout: 3s
    retries: 10
    start_period: 5s











services:

  validator1:
    << : *quorum-def
    ports:
      - 21001:8545/tcp
      - 30303
    environment:
      - GOQUORUM_CONS_ALGO=${GOQUORUM_CONS_ALGO}
      - GOQUORUM_GENESIS_MODE=standard
    volumes:
      - ./config/nodes/validator1:/config/keys
      - ./config/permissions:/permissions
    networks:
      quorum-dev-quickstart:
        ipv4_address: 172.16.239.11

  validator2:
    << : *quorum-def
    ports:
      - 21002:8545/tcp
      - 30303
    environment:
      - GOQUORUM_CONS_ALGO=${GOQUORUM_CONS_ALGO}
      - GOQUORUM_GENESIS_MODE=standard
    volumes:
      - ./config/nodes/validator2:/config/keys
      - ./config/permissions:/permissions
    networks:
      quorum-dev-quickstart:
        ipv4_address: 172.16.239.12

  validator3:
    << : *quorum-def
    ports:
      - 21003:8545/tcp
      - 30303
    environment:
      - GOQUORUM_CONS_ALGO=${GOQUORUM_CONS_ALGO}
      - GOQUORUM_GENESIS_MODE=standard
    volumes:
      - ./config/nodes/validator3:/config/keys
      - ./config/permissions:/permissions
    networks:
      quorum-dev-quickstart:
        ipv4_address: 172.16.239.13

  validator4:
    << : *quorum-def
    ports:
      - 21004:8545/tcp
      - 30303
    environment:
      - GOQUORUM_CONS_ALGO=${GOQUORUM_CONS_ALGO}
      - GOQUORUM_GENESIS_MODE=standard
    volumes:
      - ./config/nodes/validator4:/config/keys
      - ./config/permissions:/permissions
    networks:
      quorum-dev-quickstart:
        ipv4_address: 172.16.239.14

  validator5:
    << : *quorum-def
    ports:
      - 21005:8545/tcp
      - 30303
    environment:
      - GOQUORUM_CONS_ALGO=${GOQUORUM_CONS_ALGO}
      - GOQUORUM_GENESIS_MODE=standard
    volumes:
      - ./config/nodes/validator5:/config/keys
      - ./config/permissions:/permissions
    networks:
      quorum-dev-quickstart:
        ipv4_address: 172.16.239.16

  validator6:
    << : *quorum-def
    ports:
      - 21006:8545/tcp
      - 30303
    environment:
      - GOQUORUM_CONS_ALGO=${GOQUORUM_CONS_ALGO}
      - GOQUORUM_GENESIS_MODE=standard
    volumes:
      - ./config/nodes/validator6:/config/keys
      - ./config/permissions:/permissions
    networks:
      quorum-dev-quickstart:
        ipv4_address: 172.16.239.17

  validator7:
    << : *quorum-def
    ports:
      - 21007:8545/tcp
      - 30303
    environment:
      - GOQUORUM_CONS_ALGO=${GOQUORUM_CONS_ALGO}
      - GOQUORUM_GENESIS_MODE=standard
    volumes:
      - ./config/nodes/validator7:/config/keys
      - ./config/permissions:/permissions
    networks:
      quorum-dev-quickstart:
        ipv4_address: 172.16.239.18

  rpcnode:
    << : *quorum-def
    ports:
      - 9545:8545/tcp
      - 9546:8546/tcp
      - 30303
    environment:
      - GOQUORUM_CONS_ALGO=${GOQUORUM_CONS_ALGO}
      - GOQUORUM_GENESIS_MODE=standard
    volumes:
      - ./config/nodes/rpcnode:/config/keys
      - ./config/permissions:/permissions
    networks:
      quorum-dev-quickstart:
        ipv4_address: 172.16.239.15




  explorer:
    image: consensys/quorum-explorer:${QUORUM_EXPLORER_VERSION:-latest}
    volumes:
      - ./quorum-explorer/config.json:/app/config.json
      - ./quorum-explorer/env:/app/.env.production
    depends_on:
      - rpcnode
    ports:
      - 25000:25000/tcp
    networks:
      quorum-dev-quickstart:
        ipv4_address: 172.16.239.31







  loki:
    image: "grafana/loki:2.8.4"
    volumes:
      - ./loki/loki.yml:/etc/loki/local-config.yaml:ro
    command: -config.file=/etc/loki/local-config.yaml
    ports:
      - 3100:3100/tcp
    networks:
      quorum-dev-quickstart:
        ipv4_address: 172.16.239.34

  promtail:
    image: "grafana/promtail:2.8.4"
    volumes:
      - ./logs:/var/log
      - ./promtail/promtail.yml:/etc/promtail/config.yml:ro
    command: -config.file=/etc/promtail/config.yml
    networks:
      quorum-dev-quickstart:
        ipv4_address: 172.16.239.35



networks:
  quorum-dev-quickstart:
    name: quorum-dev-quickstart
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.16.239.0/24

volumes:
  splunk:
  ethlogger:
  blockscoutpostgres:
